// Package swaggerHandlers Code generated by swaggo/swag. DO NOT EDIT
package swaggerHandlers

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/captcha/generate": {
            "get": {
                "description": "Allows a client (with Client-R-ID) to generate a captcha",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get a captcha",
                "operationId": "GenerateCaptchaV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Client-R-ID",
                        "name": "Client-R-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/captchaHandlers.GetCaptchaResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/ban": {
            "post": {
                "description": "Allows a user to ban another user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Ban a user",
                "operationId": "banUserV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Ban user data",
                        "name": "banUserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/BanUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/BanUserResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/changePassword": {
            "post": {
                "description": "Allows a user to change a user's password.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Change a user's password",
                "operationId": "changePasswordV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Change password data",
                        "name": "changePasswordData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ChangePasswordData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/confirmChangePassword": {
            "post": {
                "description": "Allows a user to confirm changing their own's password (from redirected page)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Confirm changing your own's password",
                "operationId": "confirmChangePasswordV1",
                "parameters": [
                    {
                        "description": "Confirm change password data",
                        "name": "confirmChangePasswordData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/ConfirmChangePasswordData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "type": "boolean"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/create": {
            "post": {
                "description": "Allows a user to create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a new user",
                "operationId": "createUserV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Create user data",
                        "name": "createUserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/CreateUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/CreateUserResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/edit": {
            "post": {
                "description": "Allows a user to edit another user. Users are not allowed to edit their own information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Edit a user's basic information",
                "operationId": "editUserV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Edit user data",
                        "name": "editUserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/EditUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/EditUserResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "description": "Allows a user to get another user's information by their user ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get a user's information",
                "operationId": "getUserInfoV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/GetUserInfoResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/login": {
            "post": {
                "description": "Allows a user to login to the system and obtain access/refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login to the system",
                "operationId": "loginV1",
                "parameters": [
                    {
                        "description": "Login data",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/LoginResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/me": {
            "get": {
                "description": "Allows a user to get their own information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get the user's information",
                "operationId": "getMeV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/GetMeResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/reAuth": {
            "post": {
                "description": "Allows a user to refresh their access token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Refresh the access token",
                "operationId": "reAuthV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Refresh token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/AuthResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/user/search": {
            "post": {
                "description": "Allows a user to search for users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Search users",
                "operationId": "searchUserV1",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Search user data",
                        "name": "searchUserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/SearchUserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/EndpointResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "result": {
                                            "$ref": "#/definitions/SearchUserResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "APIErrorCode": {
            "type": "integer",
            "enum": [
                2100,
                2101,
                2102,
                2103,
                2104,
                2105,
                2106,
                2107,
                2108,
                2109,
                2110,
                2111,
                2112,
                2113,
                2114,
                2115,
                2116,
                2117,
                2118,
                2119,
                2120,
                2121,
                2122,
                2123,
                2124,
                2125,
                2126,
                2127,
                2128,
                2129,
                2130,
                2131,
                2132,
                2133,
                2134,
                2135,
                2136,
                2137,
                2138,
                2139,
                2140,
                2141,
                2142
            ],
            "x-enum-varnames": [
                "ErrCodeMalformedJWT",
                "ErrCodeInvalidJWT",
                "ErrCodeInvalidBodyData",
                "ErrCodeInvalidUsernamePass",
                "ErrCodeInvalidAuth",
                "ErrCodePermissionDenied",
                "ErrCodeInvalidInputPass",
                "ErrCodeUsernameExists",
                "ErrCodeInternalServerError",
                "ErrCodeInvalidFileData",
                "ErrCodeInvalidPhoneNumber",
                "ErrCodePhoneNumberAlreadyImported",
                "ErrCodeInvalidUsername",
                "ErrCodeNoPhonesDonated",
                "ErrCodeAgentNotConnected",
                "ErrCodeInvalidPagination",
                "ErrCodeMaxContactImportLimit",
                "ErrCodePhoneNumberNotFound",
                "ErrCodeParameterRequired",
                "ErrCodeUserBanned",
                "ErrCodeLabelInfoNotFound",
                "ErrCodeLabelAlreadyApplied",
                "ErrCodeLabelAlreadyExistsByName",
                "ErrCodeTooManyChatLabelInfo",
                "ErrCodeLabelNameTooLong",
                "ErrCodeLabelDescriptionTooLong",
                "ErrCodeInvalidColor",
                "ErrCodeLabelNotApplied",
                "ErrCodeCannotDeleteBuiltInLabel",
                "ErrCodeDuplicatePhoneNumber",
                "ErrCodePhoneNotWorking",
                "ErrCodeInvalidPmsPass",
                "ErrCodeInvalidAgentId",
                "ErrCodeInvalidAppSettingName",
                "ErrCodeAppSettingNotFound",
                "ErrCodeTextEmpty",
                "ErrCodeTextTooLong",
                "ErrCodeInvalidClientRId",
                "ErrCodeInvalidCaptcha",
                "ErrCodeQueryParameterNotProvided",
                "ErrCodeTooManyPasswordChangeAttempts",
                "ErrCodeRequestExpired",
                "ErrCodeInvalidEmail"
            ]
        },
        "AuthResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expiration": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "BanUserData": {
            "type": "object",
            "properties": {
                "ban_reason": {
                    "type": "string"
                },
                "is_banned": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "BanUserResult": {
            "type": "object",
            "properties": {
                "ban_reason": {
                    "type": "string"
                },
                "is_banned": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ChangePasswordData": {
            "type": "object",
            "properties": {
                "lang": {
                    "type": "string",
                    "default": "en"
                },
                "new_password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "ConfirmChangePasswordData": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "rq_id": {
                    "type": "string"
                },
                "rt_hash": {
                    "type": "string"
                },
                "rt_param": {
                    "type": "string"
                },
                "rt_verifier": {
                    "type": "string"
                }
            }
        },
        "CreateNewTopicData": {
            "type": "object",
            "properties": {
                "topicName": {
                    "type": "string"
                }
            }
        },
        "CreateNewTopicResult": {
            "type": "object",
            "properties": {
                "topicID": {
                    "type": "integer"
                },
                "topicName": {
                    "type": "string"
                }
            }
        },
        "CreateUserData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/UserRole"
                },
                "setup_completed": {
                    "type": "boolean"
                },
                "user_address": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "CreateUserResult": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "EditUserData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "user_address": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "EditUserResult": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/UserRole"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "EndpointError": {
            "type": "object",
            "properties": {
                "code": {
                    "$ref": "#/definitions/APIErrorCode"
                },
                "date": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                }
            }
        },
        "EndpointResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/EndpointError"
                },
                "result": {},
                "success": {
                    "type": "boolean"
                }
            }
        },
        "GetMeResult": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/UserRole"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "GetUserInfoResult": {
            "type": "object",
            "properties": {
                "ban_reason": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "is_banned": {
                    "type": "boolean"
                },
                "role": {
                    "$ref": "#/definitions/UserRole"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "LoginData": {
            "type": "object",
            "properties": {
                "captcha_answer": {
                    "type": "string"
                },
                "captcha_id": {
                    "type": "string"
                },
                "client_rid": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "LoginResult": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expiration": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/UserRole"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "SearchUserData": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "minimum": 1
                },
                "offset": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                }
            }
        },
        "SearchUserResult": {
            "type": "object",
            "properties": {
                "users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SearchedUserInfo"
                    }
                }
            }
        },
        "SearchedUserInfo": {
            "type": "object",
            "properties": {
                "ban_reason": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "is_banned": {
                    "type": "boolean"
                },
                "role": {
                    "$ref": "#/definitions/UserRole"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "UserRole": {
            "description": "UserRole is the role of the user.",
            "type": "string",
            "enum": [
                "owner",
                "admin",
                "student",
                "teacher",
                ""
            ],
            "x-enum-varnames": [
                "UserRoleOwner",
                "UserRoleAdmin",
                "UserRoleStudent",
                "UserRoleTeacher",
                "UserRoleUnknown"
            ]
        },
        "captchaHandlers.GetCaptchaResult": {
            "type": "object",
            "properties": {
                "captcha": {
                    "type": "string"
                },
                "captcha_id": {
                    "type": "string"
                },
                "client_r_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "ExamSphere API",
	Description:      "This is the API for the ExamSphere system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
